name: "swinir"
description: "swinir_short"
description_long: "swinir_long"
link: https://github.com/JingyunLiang/SwinIR


examples:
   image1: image1out
   image2: image2out

miniatures:
   input: output

environment: standard