name: "swinir"
description: "swinir_short"
description_long: "swinir_long"
link: https://github.com/JingyunLiang/SwinIR


examples:
   katzein.jpg: katzeout.png
   nin.jpg: nout.png

miniatures:
   input: output

environment: standard