name: "wb"
description: "wb_short"
description_long: "wb_long"
link: https://github.com/yanxiang-wang/mixedillWB

examples:
   image1: image1out
   image2: image2out

miniatures:
   input: output

environment: whitebalance