name: "nafnet"
description: "nafnet_short"
description_long: "nafnet_long"
link: https://github.com/megvii-research/NAFNet


examples:
   image1: image1out
   image2: image2out

miniatures:
   input: output

environment: nafnet