name: "nafnet"
description: "nafnet_short"
description_long: "nafnet_long"
link: https://github.com/megvii-research/NAFNet


examples:
   blurryin.png: blurryout.png
   noisyin.png: noisyout.png

environment: nafnet