name: "llie"
description: "llie_short"
description_long: "llie_long"
link: https://github.com/pvnieo/Low-light-Image-Enhancement

examples:
  image1: image1out
  image2: image2out

miniatures:
  input: output

environment: lowlight