name: "gpen"
description: "gpen_short"
description_long: "gpen_long"
link: https://github.com/yangxy/GPEN


examples:
   enhancementin.png: enhancementout.png
   colorizationin.png: colorizationout.png
   inpaintingin.png: inpaintingout.png

miniatures:
   input: output

environment: gpen