name: "LLFlow"
description: "A tool to enhance dark Images"

examples:
  image1.png: image1out.png
  image2.png: image2out.png
  image3.png: image3out.png

miniatures:
  input: output

environment: lowlight2